### ISSUE TITLE
Remove dependency on libstdc++

### ISSUE THREAD

**Issue by newhoggy** [chadaustin/buffer-builder#18]
This fails to build in the absence of `libstdc++`.  Looking at the source code it doesn't look like the c-bits actually use any C++ functionality.

**Comment by chadaustin** [comment]
I'd support this change. I don't have time to implement it immediately but if you want to put together a PR I could get it landed and released.

**Comment by chadaustin** [comment]
This dependency was added as part of https://github.com/chadaustin/buffer-builder/pull/12

@robdockins Can you clarify what systems needed this change?

I tried to convert the .cpp files to .c last night but I couldn't figure out how to convince Cabal to build them in C mode rather than C++ mode. If I could reproduce @robdockins's original issue, it probably wouldn't be hard to break the dependency on libstdc++.

**Comment by robdockins** [comment]
Sorry, I've paged out the original context for that request... I think it may have been Windows builds that were causing me trouble at the time, but I don't recall for sure.

**Comment by chadaustin** [comment]
0.2.4.7 is released with all of the FFI bits replaced with C99 instead of C++ code.

**Comment by newhoggy** [comment]
Thanks!
